version: '3.8'

services:
  postgresdb:
    image: postgres:16-alpine
    container_name: todomanager-db
    restart: always 
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
        - "5432:5432" 
    
  todomanager:
    image: ${DOCKER_REGISTRY-}todomanager
    build:
      context: .
      dockerfile: TodoManager/Dockerfile
    container_name: todomanager-api
    ports:
        - "8080:8080" 
        - "8081:8081"
    
    depends_on:
      - postgresdb
      
    environment:
      ConnectionStrings__DefaultConnection: Host=postgresdb;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}

networks:
  default:
    driver: bridge

volumes:
  postgres_data: