name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - master 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' 

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build TodoManager.API/TodoManager.API.csproj --configuration Release

    - name: Run tests
      run: dotnet test TodoManager.Tests/TodoManager.Tests.csproj --configuration Release --verbosity normal

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Start SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy via Git pull and Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.196.152.174 "
          cd ~/TodoManager.API &&
          git reset --hard origin/master &&
          git pull origin master &&
          docker-compose down &&
          docker-compose up -d --build
        "
